media: 
  - name: Media
    input: public
    output: /
content: 
  - name: posts
    label: Posts
    type: collection
    path: app/_posts
    fields:
    - {name: title, label: Title, type: string}
    - {name: description, label: Description, type: string}
    - {name: date, label: Date, type: date}
    - {name: author, label: Author, type: string}
    - {name: category, label: Category, type: string}
    - {name: tags, label: Tags, type: string}
    - {name: image, label: Image, type: image}
    - {name: body, label: Body, type: rich-text}
content:
   - name: data
     label: Data
     type: collection
     path: app/content