media: public
content: 
  - name: posts
    label: Posts
    type: collection
    path: app/_posts
    fields:
    - {name: title, label: Title, type: string}
    - {name: description, label: Description, type: string}
    - {name: date, label: Date, type: date}
    - {name: author, label: Author, type: string}
    - {name: category, label: Category, type: string}
    - {name: tags, label: Tags, type: string}
    - {name: tags, label: Tags, type: image}
